### ISSUE TITLE
此教程极差, 新手别学这个

### ISSUE THREAD

**Issue by mawelture** [puppyapple/Chinese_LLM_From_Scratch#1]
很多关键点作者都没放出来, litgpt教程网上资料也很少, 写的也模模糊糊的, 需要花大量时间去摸索, 新手别试了, 看别的教程吧

**Comment by puppyapple** [comment]
> 很多关键点作者都没放出来, litgpt教程网上资料也很少, 写的也模模糊糊的, 需要花大量时间去摸索, 新手别试了, 看别的教程吧

1. 我从来没说这个项目是个教程， 这是我自己学习的一个记录而已；
2. 分享出来对别人有帮助自然最好，没帮助就罢了；你看得懂看不懂关我何事？
3. 你一个看资料的，连前期评估东西是否适合自己的能力都没有，然后给人一个「极差」的标签？
4. 我的记录里列出了大量我自己学习时候参考的其他大神的「教程」，都写的很好，但也会有不清晰或者有问题的地方；有问题就问，有建议就提不好么？
